travis:
  secure:
    BINSTAR_TOKEN: aY26+eKOJsmL3zjs7EJubf0AhY8X17wL4knSRrtlHkn0y25L2/switGZ6rLTAwFz5sjEupt1SSCVhMwPkCczziUSddvTX4weG0oVFlNwQ0z8b2md1XNxC4ldt2lWTy+dUciQsVrdwU3Xk1JVDigp85lWN3BX63zNjOdMO7MYzGJaqi7F7JX1ODu8OkFO8KjSfqbAQSIYdO/bko/svxKRfY967g7FI9fpQchTkhrgAizebP0OqTJHrwYMPItGCDY6o8cpSkDNQyDaen1fYBHh63Nb0mwlkuHEPqhDi/aDtAOZi8A8eUpBaqazANiP+GlvZChmw0YRFBT4tciMKTV4OIDR0Hc4e7JZrV828K30KSjxKJFp259o+du3vBhv/VaFVfkmohwUQZyAjR7Rs4AoVH52/XyxpK83L84Q2Muo/1FWobLeqkTJA64AHRKtwzlIj+lNCdTuQNu6KNZgA3ZmO2DxuE9+LvwOGT3unzloFBHmmgoqjnXs+dAzz6JHMTmNAwXQwRwulYbrrL6AMg3u6TeVkAFOnWAL3EpKuMKGVho5xqNGxN6YrsBe8e8iG8couCxDcSkIdX4KYHIIjG9FKz2mxK3X79SbsMU8osM8TUxbjesOTXdpAElh/gc/64tJ1t+KIqxVWbxt7eZtRWPez5UuOMVVMHkaPs2hj6NCnoQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
